### ISSUE TITLE
Remember last used node

### ISSUE THREAD

**Issue by fyrak1s** [Qortal/qortal-ui#152]
Hi, I hope "feature requests" are ok here :)

I think it would be very useful if Qortal UI would remember the last selected node.

Explanation: Personally I am using a custom node, but _every time_ I close and open Qortal UI, I have to remember to select my custom node before login. I think the UI should remember the last selection even after restart.

**Comment by AlphaX-Projects** [comment]
yeah i know but this is because you can start ui from any browser and we have to an extra localstorage for that
I will recheck

**Comment by QuickMythril** [comment]
Thank you. The suggestion above has been implented. This should be resolved.
