### ISSUE TITLE
Wallet Profile Blank on New Accounts

### ISSUE THREAD

**Issue by Pigpig105** [Qortal/qortal-ui#154]
I think we just have to make it show the default "question mark" avatar, to fix the issue.  Otherwise it will not show, blocks minted, address, etc.

**Comment by AlphaX-Projects** [comment]
@Pigpig105 wasn't it your commit ?

**Comment by Pigpig105** [comment]
Yes but I cannot figure out a solution.  Looks to me like if they haven't registered a name or any tx or anything, it won't show wallet profile AT ALL.  I have it set in the html on the img tag to do "onerror" display the incognito, but it didn't work.  So maybe we need something like:

if name is not registered, then show old wallet profile, if name is registered, show new wallet profile.  Something like that.  I can't figure out how to do it myself.
