### ISSUE TITLE
Mixed case of names lost during Group creation

### ISSUE THREAD

**Issue by Mark-BC** [Qortal/qortal-ui#162]
When I create a Group with a mixed-case name, the name string is reduced to lower case and the group is created that way.
From then on the user is forced to view the lower-case name.

Suggestion:  The UI should respect the case of the name, even if the internals want to lower-case everything for their own purposes.  Just let the user know that case doesn't matter when searching for names, but always show the name as it was entered by the group creator.

**Comment by AlphaX-Projects** [comment]
This is not from ui side,.
This is a core side thing, please post there

**Comment by QuickMythril** [comment]
This issue has been opened in the Core repo, as it's not related to the UI.
https://github.com/Qortal/qortal/issues/121

EDIT:  I was mistaken, and this is in fact caused by the UI.
A new Pull Request has been opened to fix it:
https://github.com/Qortal/qortal-ui/pull/287
