### ISSUE TITLE
ADD: (Login) Edit / delete custom node entries

### ISSUE THREAD

**Issue by fyrak1s** [Qortal/qortal-ui#165]
This is kind of a follow up to #152. On my end the entries are clogging up and I have no comfortable way to delete them thorugh the UI. The only option for me would be to "REMOVE ALL CUSTOM NODES", but then I would have to redo everything, even if I need to delete only one or two of them.. This happens a lot when I make a typo or test out stuff.

I did a mockup how this could be achieved within the current UI:
![quortal_node_](https://github.com/Qortal/qortal-ui/assets/2538022/36766ee7-ea61-42cf-949f-9e7c0d77f8c1)

I know every feature means practical work, and it doesn't need to be here tomorrow, but for me this would aid the user experience a lot (kind of a basic feature tbh).

Thank you :)

**Comment by fyrak1s** [comment]
Ty for making it happen!

Btw I had been trying to do this myself but couldn't figure it out. Would you kindly point me to the commit that implemented this, so that I can take a look?

**Comment by Philreact** [comment]
here's the commit
https://github.com/Qortal/qortal-ui/commit/28c58cb2496b46754dc9422c3c210c3ddcb9e71b
