### ISSUE TITLE
Q-Mail Tab Button

### ISSUE THREAD

**Issue by Pigpig105** [Qortal/qortal-ui#195]
The "mail" icon on the upper right of the UI that shows Q-Mail notifications.  When you click it, it opens Q-Mail, but doesn't say that on the tab name.  It just says "New Tab"

**Comment by crowetic** [comment]
I do not have this issue, when I click it, it says Q-Mail. (but I am using phil's pre-release version, so potentially this is already fixed.)

**Comment by Pigpig105** [comment]
His UI is no longer available here https://cloud.qortal.org/s/oBLMQ5D7ssb5a5Y

**Comment by Pigpig105** [comment]
Okay.  This is the new link https://cloud.qortal.org/s/eFpsZxL29KZ4z2J
Here is the github link https://github.com/Philreact/qortal-ui/tree/feature/improve-image-qchat

I just built the UI from source.  I can confirm this UI fixes this issue.  Thanks for the feedback, closing the issue since it is already resolved, just not merged.
