### ISSUE TITLE
Q-Apps Plugin Refresh Page Issue

### ISSUE THREAD

**Issue by Pigpig105** [Qortal/qortal-ui#227]
If you click download on a Q-App on page 2, after it is finished downloading the UI automatically refreshes the page.  It SHOULD stay on page two.  However it shows you page one.  So not only is it showing you the wrong page, but it also shows you the wrong page number.  It is showing you are you on page number two but listing page one Q-Apps.

**Comment by AlphaX-Projects** [comment]
@Pigpig105 the new q-app page is uploaded there you have no more pages !
![image](https://github.com/Qortal/qortal-ui/assets/77661270/f6a0f879-9c64-441d-bc1f-442891519a95)

**Comment by Pigpig105** [comment]
Awesome it looks great!  Closing the Issue
