### ISSUE TITLE
UI chat group list scroll on Mac

### ISSUE THREAD

**Issue by hermes2artemis** [Qortal/qortal-ui#234]
There is an issue with scrolling through chat group list since UI 4.4.3 - it doesn't...

Some have found that clicking on a group and clicking down/up arrow will get the scroll bar to appear and that clicking on a group and clicking up/down arrow will get the list to move one place at a time - need to click the group again to move another place. Thanks

**Comment by AlphaX-Projects** [comment]
@hermes2artemis can you please tell me which macos you are running, so i can test on my macs.

**Comment by hermes2artemis** [comment]
2016 MacBook Pro 13 inch macOS Monterey 12.7
(not sure about the others, will ask...)

**Comment by AlphaX-Projects** [comment]
Ok i have on 2015 MacBook Pro 13 inch with macOS BigSur 13.6 will test there

**Comment by AlphaX-Projects** [comment]
Tested on BigSur and dont have prob there

**Comment by teamak2020** [comment]
11.7.10 (20G1427)

**Comment by hermes2artemis** [comment]
Thanks - looking forward to it!
