### ISSUE TITLE
qortal-ui 4.4.4: Tour opening at the same time as the modal for entering API key renders wallet unusable

### ISSUE THREAD

**Issue by allyouracid** [Qortal/qortal-ui#246]
Good evening,

I recently had a fresh OS install, had to set up everything from scratch. So, naturally, the UI asked me to enter the API key. But when the tour also opens (both on top of each other), I can reach neither element. Can't enter the API key and can't click away the tour. So, something seems to be wrong with the alignment of the elements on the z axis.

Just a fyi... for the time being, I switched back to 4.4.3 which doesn't have the tour, yet. :)

**Comment by QuickMythril** [comment]
this should be fixed already with the following commit, which will be in the next release.

https://github.com/Qortal/qortal-ui/commit/1ec38d2ff5af9b1bc898f641acf2f269b0f4ade7

**Comment by allyouracid** [comment]
Oh perfect, then this issue is actually a non-issue. I'll close it.
