### ISSUE TITLE
v4.5.0 macOS - Wrong Files

### ISSUE THREAD

**Issue by QuickMythril** [Qortal/qortal-ui#253]
Qortal UI v4.3.0 files were uploaded for macOS.  here's an alternate link until that is fixed:
https://github.com/QuickMythril/qortal-ui/releases

Someone reported in Q-Chat seeing 4.3.0 in the UI upon installing v4.5.0 dmg file.
See: https://github.com/Qortal/qortal-ui/releases
The checksums for v4.3.0 & v4.5.0 are identical at the time of this post, for all macOS files.

MD5: `9b7a2455c0c37df024959baac17a3dca` Qortal-Setup-macOS.zip
MD5: `c8778fcfb44817df67cad9e86795e62b` Qortal-Setup-macOS.pkg
MD5: `d7111d9ac6356790c9bb64d0f460d235` Qortal-Setup-macOS.dmg
SHA1: `c06a85f32b2cac4ee86c5004ef5d741968dabeba` Qortal-Setup-macOS.zip
SHA1: `a25bbfc65355bf62c4c057df3af53274722b4814` Qortal-Setup-macOS.pkg
SHA1: `82d5eeba5f4325cfa68db7872c797ef3bf5d5e0e` Qortal-Setup-macOS.dmg
SHA256: `763c8c493af2134bbd6ece7f4a1bccdfb996dc9e02dbc878dc54768a86ae864f` Qortal-Setup-macOS.zip
SHA256: `c9f7cf2b33802a98178bc2b5b37db4f35ecf205fb91bae5e1b1dd00851655be0` Qortal-Setup-macOS.pkg
SHA256: `2cfd7395b5734e7f30db88a764bb0697cec61ae3ae6013a5813eea31a82b1a89` Qortal-Setup-macOS.dmg

**Comment by AlphaX-Projects** [comment]
Fixed
