### ISSUE TITLE
Foreign characters not supported in some Q-Apps 

### ISSUE THREAD

**Issue by QuickMythril** [Qortal/qortal-ui#272]
In Q-Chat, someone reported that they were unable to use foreign characters (like Chinese) in various fields of some of the main Q-Apps, like Q-Tube and Q-Blog.  They said that the fee was still processed and paid, but the publish failed and the content was not available.  This information was also posted into the Q-Apps Development chat group, and is being reposted here so it doesn't get overlooked.

**Comment by QuickMythril** [comment]
https://t.me/qortal_official/133558
`I dont know who is responsable for Q-Tube but I would apreciate the ability to write special characters like ś ź ń ć ę ł ą and so on in the titles of the videos, as it is not possible now`

**Comment by iffinland** [comment]
I also checked whether the dot letters used when writing in Estonian and Finnish work, maybe in some other languages as well.
Can't enter the dot letters in the video title, but they work very well in the description

https://t.me/qortal_official/133564

**Comment by QortalSeth** [comment]
I know what's causing that, and I'll fix it soon.
