### ISSUE TITLE
macOS scrolling issues

### ISSUE THREAD

**Issue by QuickMythril** [Qortal/qortal-ui#304]
i am not sure exactly what the problem is with scrolling on mac, as i have not been able to test it for myself, but i have seen multiple people reporting issues with it.  they said it was fixed in one of the prereleases, but in the 4.5.2 release it was a problem again.  from what i could tell, it's got to do with this commit, where electron was rolled back in the prerelease.  however in the release version, it was upgraded to v30 again.  i am not sure what the best option to resolve this, but i don't think we should continue using an end of life version just for compatibility.  we might need to get more feedback from users to understand the problem better, in order to find a solution.

Related commit that had seemingly resolved the problems:
Rollback electron to v27 ( mac compatibility ) - https://github.com/Qortal/qortal-ui/pull/271/commits/732f3f97f2e8720935310a028cf62bfac487309a

**Comment by QuickMythril** [comment]
here is some of the chat that led me to opening this issue:

`"The non-scrolling bar bug fix for Mac users wasn't included in the update"` ... `"here in the chat on the left."` ... `"I can access the scroll bar and move it manually"` ... `"on their macs cannot see the bar so rely on mouse plus keyboard to scroll"`

it seems this is related to scrolling the chat group list on the left side of the Q-Chat plugin.  some users are seeing different results, presumably based on different OS versions, but i am not sure.

**Comment by QuickMythril** [comment]
some users have tested the current UI build, and it doesn't seem like it's working still.  the build includes this commit, which i think was supposed to fix it, but it hasn't:

https://github.com/Qortal/qortal-ui/commit/555aa1bc07c0684aabeeafc6ce20fa03eb4a7421
Added vaadin scroller for mac os compatibility

to be clear, it's the Group List on the left side of Q-Chat, where it shows the Groups you are in, and any Private Messages that are active.

**Comment by QuickMythril** [comment]
also i just realized this is a duplicate issue of https://github.com/Qortal/qortal-ui/issues/234 (UI chat group list scroll on Mac)

**Comment by QuickMythril** [comment]
someone in Q-Chat says:

"I can see the scroll bar on my iMac and I use the mouse to grab it, but I think the macbooks that others are using can't even see the scroll bar and have to use keyboard shortcuts.  all scroll bars on everything else in qortal work."

**Comment by hermes2artemis** [comment]
thanks Quick and Alpha
